[Bestanden]
; Centrale locatie van het voorbladtemplate
template = D:\OD\TOOL Engineers BV\Templates\Voorblad.docx

; Centrale locatie van het TOOL Engineers logo
logo = D:\OD\TOOL Engineers BV\TOOL - Documenten\00 - TOOL\01 - PR TOOL\01 - Logo\TOOL Engineers 15-07-2024.png


[Uitvoer]
; Standaardmap waarin de gegenereerde PDF wordt opgeslagen
map = D:\OD\TOOL Engineers BV\Gegenereerde PDF

; Complete samengestelde PDF genereren
complete_pdf = true

; Bijlagen daarnaast ook afzonderlijk opslaan
separate_files = false


[PDF]
; Maximale toegestane bestandsgrootte in MB
; 0 = controle uitgeschakeld
max_size_mb = 15